targets:
  $default:
    builders:
      retrofit_generator:
        options:
          auto_cast_response: true
          format_output: false
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
